
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-ui
  namespace: ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-ui
  template:
    metadata:
      labels:
        app: kafka-ui
    spec:
      containers:
        - name: kafka-ui
          image: provectuslabs/kafka-ui:latest
          ports:
            - containerPort: 8080
          env:
            - name: DYNAMIC_CONFIG_ENABLED
              value: "true"
            - name: KAFKA_CLUSTERS_0_NAME
              value: local-cluster
            - name: KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS
              value: kafka-broker:29092

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-service
  namespace: ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders-service
  template:
    metadata:
      labels:
        app: orders-service
    spec:
      containers:
        - name: orders-service
          image: wagnerwutzke/orders-service:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9000
          env:
            - name: APP_PORT
              value: "9000"
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: kafka-broker:29092
          volumeMounts:
            - name: orders-data
              mountPath: /data/db/orders
      volumes:
        - name: orders-volume
          persistentVolumeClaim:
            claimName: orders-pvc

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: customers-service
  namespace: ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customers-service
  template:
    metadata:
      labels:
        app: customers-service
    spec:
      containers:
        - name: customers-service
          image: wagnerwutzke/customers-service:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9010
          env:
            - name: APP_PORT
              value: "9010"
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: kafka-broker:29092
          volumeMounts:
            - name: customers-data
              mountPath: /data/db/customers
      volumes:
        - name: customers-volume
          persistentVolumeClaim:
            claimName: customers-pvc

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-service
  namespace: ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-service
  template:
    metadata:
      labels:
        app: inventory-service
    spec:
      containers:
        - name: inventory-service
          image: wagnerwutzke/inventory-service:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9020
          env:
            - name: APP_PORT
              value: "9020"
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: kafka-broker:29092
          volumeMounts:
            - name: inventory-data
              mountPath: /data/db/inventory
      volumes:
        - name: inventory-volume
          persistentVolumeClaim:
            claimName: inventory-pvc

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-service
  namespace: ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments-service
  template:
    metadata:
      labels:
        app: payments-service
    spec:
      containers:
        - name: payments-service
          image: wagnerwutzke/payments-service:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9030
          env:
            - name: APP_PORT
              value: "9030"
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: kafka-broker:29092
          volumeMounts:
            - name: payments-data
              mountPath: /data/db/payments
      volumes:
        - name: payments-volume
          persistentVolumeClaim:
            claimName: payments-pvc

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: invoices-service
  namespace: ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: invoices-service
  template:
    metadata:
      labels:
        app: invoices-service
    spec:
      containers:
        - name: invoices-service
          image: wagnerwutzke/invoices-service:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9040
          env:
            - name: APP_PORT
              value: "9040"
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: kafka-broker:29092
          volumeMounts:
            - name: invoices-data
              mountPath: /data/db/invoices
      volumes:
        - name: invoices-data
          persistentVolumeClaim:
            claimName: invoices-pvc

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipments-service
  namespace: ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shipments-service
  template:
    metadata:
      labels:
        app: shipments-service
    spec:
      containers:
        - name: shipments-service
          image: wagnerwutzke/shipments-service:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9050
          env:
            - name: APP_PORT
              value: "9040"
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: kafka-broker:29092
          volumeMounts:
            - name: shipments-data
              mountPath: /data/db/shipments
      volumes:
        - name: shipments-data
          persistentVolumeClaim:
            claimName: shipments-pvc

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka-broker
  namespace: ecommerce
spec:
  serviceName: kafka-broker
  replicas: 1
  selector:
    matchLabels:
      app: kafka-broker
  template:
    metadata:
      labels:
        app: kafka-broker
    spec:
      containers:
        - name: kafka-broker
          image: confluentinc/cp-kafka:8.3.1
          ports:
            - name: external
              containerPort: 9092
            - name: internal
              containerPort: 29092
            - name: controller
              containerPort: 9093
          env:
            - name: CLUSTER_ID
              value: WnLkTHhkQaiJbwP8FClPhw
            - name: KAFKA_NODE_ID
              value: "1"
            - name: KAFKA_PROCESS_ROLES
              value: broker,controller
            - name: KAFKA_CONTROLLER_QUORUM_VOTERS
              value: 1@kafka-broker:9093
            - name: KAFKA_LISTENERS
              value: PLAINTEXT://0.0.0.0:29092,CONTROLLER://0.0.0.0:9093,EXTERNAL://0.0.0.0:9092
            # Internal clients use kafka-broker:29092. Local clients use localhost:30092.
            - name: KAFKA_ADVERTISED_LISTENERS
              value: PLAINTEXT://kafka-broker:29092,EXTERNAL://localhost:30092
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
            - name: KAFKA_CONTROLLER_LISTENER_NAMES
              value: CONTROLLER
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: PLAINTEXT
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS
              value: "0"
            - name: KAFKA_LOG_DIRS
              value: /var/lib/kafka/data
          volumeMounts:
            - name: kafka-data
              mountPath: /data/db/kafka
      volumes:
        - name: kafka-volume
          persistentVolumeClaim:
            claimName: kafka-pvc