apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: ecommerce
  region: us-east-2
  version: "1.37"

managedNodeGroups:
  - name: workers
    instanceType: m7i-flex.large
    desiredCapacity: 4
    minSize: 3
    maxSize: 5
    volumeSize: 20

addons:
  - name: aws-ebs-csi-driver
    version: latest
  - name: eks-pod-identity-agent
    version: latest

addonsConfig:
  autoApplyPodIdentityAssociations: true
