apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch
  namespace: logging
spec:
  serviceName: elasticsearch # Links StatefulSet to headless service , Enables stable DNS.
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch

  template:
    metadata:
      labels:
        app: elasticsearch # Labels used by: StatefulSet, Service, DNS

    spec:
      containers:
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:7.2.0 # Elasticsearch version, Must match Kibana version.

          resources:
            limits:
              cpu: 1000m
              memory: 1Gi
            requests:
              cpu: 500m
              memory: 500Mi

          ports:
            - containerPort: 9200
              name: rest # REST API (used by Kibana, Fluent Bit).

            - containerPort: 9300
              name: inter-node  # Internal Elasticsearch cluster communication.

          volumeMounts:
            - name: data
              mountPath: /usr/share/elasticsearch/data

          env:
            - name: cluster.name
              value: k8s-logs # Logical cluster name.

            - name: node.name
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name # Each pod uses its own name (elasticsearch-0).

            - name: discovery.seed_hosts # List of all Elasticsearch pods, Required for node discovery.
              value: "elasticsearch-0.elasticsearch"

            - name: cluster.initial_master_nodes # Prevents split-brain during first startup.
              value: "elasticsearch-0"

            - name: ES_JAVA_OPTS
              value: "-Xms512m -Xmx512m" # JVM heap settings.

      initContainers: #  Run before Elasticsearch starts.
        - name: fix-permission # Fixes file ownership for mounted volume.
          image: busybox
          command: ["sh", "-c", "chown -R 1000:1000 /usr/share/elasticsearch/data"]
          securityContext:
            privileged: true
          volumeMounts:
            - name: data
              mountPath: /usr/share/elasticsearch/data

        - name: increase-vm-max-map
          image: busybox
          command: ["sysctl", "-w", "vm.max_map_count=262144"]
          securityContext:
            privileged: true

        - name: increase-fd-ulimit
          image: busybox
          command: ["sh", "-c", "ulimit -n 65536"]
          securityContext:
            privileged: true

  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]

        storageClassName: ebs-storage   # Uses AWS EBS
        resources:
          requests:
            storage: 4Gi   # Each pod gets 10GB volume
